### ISSUE TITLE
Exception on upgrade

### ISSUE THREAD

**Issue by coret** [Daniel-KM/Omeka-S-module-Log#6]
I've upgraded the Log module to today's Log-3.3.12.9. The application log shows the following error on upgrade:

```
Next Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE log DROP FOREIGN KEY FK_8F3F68C57E3C61F9':

SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP FOREIGN KEY `FK_8F3F68C57E3C61F9`; check that it exists in /home/xxxx/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:128
```

I assume this upgrade is to tackle https://github.com/Daniel-KM/Omeka-S-module-BulkExport/issues/4 ? When I now do a Bulk export I get the following error:

```
2021-08-06T10:15:41+00:00 ERR (3): Error: Class 'Doctrine\Common\Inflector\Inflector' not found in /home/xxxxx/omeka-s/modules/BulkExport/src/Api/Adapter/ExportAdapter.php:64
Stack trace:
#0 /home/xxxxx/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(607): BulkExport\Api\Adapter\ExportAdapter->hydrate()
#1 /home/xxxxx/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(318): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity()
#2 /home/xxxxx/omeka-s/application/src/Api/Manager.php(224): Omeka\Api\Adapter\AbstractEntityAdapter->create()
#3 /home/xxxxx/omeka-s/application/src/Api/Manager.php(78): Omeka\Api\Manager->execute()
#4 /home/xxxxx/omeka-s/application/src/Mvc/Controller/Plugin/Api.php(99): Omeka\Api\Manager->create()
#5 /home/xxxxx/omeka-s/modules/BulkExport/src/Controller/Admin/ExporterController.php(259): Omeka\Mvc\Controller\Plugin\Api->create()
#6 /home/xxxxx/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): BulkExport\Controller\Admin\ExporterController->startAction()
#7 /home/xxxxx/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch()
#8 /home/xxxxx/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners()
#9 /home/xxxxx/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\EventManager\EventManager->triggerEventUntil()
#10 /home/xxxxx/omeka-s/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch()
#11 /home/xxxxx/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch()
#12 /home/xxxxx/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners()
#13 /home/xxxxx/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil()
#14 /home/xxxxx/omeka-s/index.php(21): Laminas\Mvc\Application->run()
#15 {main} {"userId":1}

```

**Comment by Daniel-KM** [comment]
Indeed, `Doctrine\Common\Inflector\Inflector` have been replaced by `Doctrine\Inflector\InflectorFactory`, but it's only for version 3.1 of Omeka, that will be released in a few days or weeks. So you probably have the new version, that breaks modules. I pushed a commit that fixes it.

**Comment by Daniel-KM** [comment]
For Log, you have an old version, so I updated the upgrade in last version.
